name: pronote_notifications
description: Notifications pour Pronote

publish_to: 'none'

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  flutter_local_notifications: ^4.0.1+2
  english_words: ^3.1.5
  http: ^0.13.0
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  image_downloader: ^0.30.0
  settings_ui: ^0.4.0
  flutter_launcher_icons: ^0.9.0
  geolocator: ^7.0.1
  url_launcher: ^6.0.2

dependency_overrides:
  plugin_platform_interface: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher-icon.png"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf

  assets:
    - url-pronote.png
    - launcher-icon.png
    - bell.png
