name: pronote_notifications
description: Notifications pour Pronote

publish_to: 'none'

version: 1.1.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.1
  flutter_local_notifications: ^5.0.0+1
  english_words: ^4.0.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  settings_ui:
    git:
      url: https://github.com/EduWireApps/flutter-settings-ui.git
      ref: f9d0639
  flutter_launcher_icons: ^0.9.0
  geolocator: ^7.0.1
  url_launcher: ^6.0.3
  in_app_review: ^2.0.1
  package_info: ^2.0.0
  external_app_launcher: ^0.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher-icon.png"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf

  assets:
    - url-pronote.png
    - launcher-icon.png
    - icon.png
